[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fakeldat-cli"
path = "src/main.rs"

[dependencies]
fakeldat_lib = { path = "../fakeldat_lib" }
clap = { version = "4.5", features = ["derive"] }
